### ISSUE TITLE
hiya :P

### ISSUE THREAD

**Issue by xieyuheng** [orchid-hybrid/lain#1]
IMO, after the inner interpreter,
you have learned the good part of forth.

after learning this tech,
you can try to design something interesting
which are different from classical forth,
change some design decisions, modify implementation tech, ...
then you have your own language :)
it will be much easier and fun than to implement a "more forth-like" system.

but this is just my very personal view :)

**Comment by orchid-hybrid** [comment]
Thank you kindly xieyuheng :)
